In [1]:
import pandas as pd 
import numpy as np 
# import pyspark.pandas as ps
from pyspark.sql import SparkSession

In [2]:
import pyspark.pandas as ps

In [3]:
s = pd.Series([1,3,5,np.nan,6,8])

In [4]:
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [5]:
dates = pd.date_range('20130101',periods=6)

In [6]:
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [7]:
pdf = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))

In [8]:
pdf

                   A         B         C         D
2013-01-01 -0.442339  0.684567  0.220888 -0.219810
2013-01-02 -0.795681  0.876973  0.403456 -0.986539
2013-01-03  0.142515 -1.036737  0.149822 -0.383193
2013-01-04 -0.467101 -0.818107  0.338293 -1.072703
2013-01-05 -0.372097 -0.275077 -0.511828 -0.207617
2013-01-06  0.043129 -0.409760 -0.290485 -1.793666

In [9]:
psdf = ps.from_pandas(pdf)

WARNING: Using incubator modules: jdk.incubator.vector
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
26/10/27 10:35:28 WARN Utils: Your hostname, Usmanovs-MacBook-Pro.local, resolves to a loopback address: 127.0.0.1; using 10.25.235.138 instead (on interface en0)
26/10/27 10:35:28 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/10/27 10:35:29 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

In [13]:
type(psdf)

pyspark.pandas.frame.DataFrame

In [14]:
spark = SparkSession.builder.getOrCreate()
sdf = spark.createDataFrame(pdf)

sdf.show()

+--------------------+--------------------+--------------------+--------------------+
|                   A|                   B|                   C|                   D|
+--------------------+--------------------+--------------------+--------------------+
|-0.44233890479476007|  0.6845668549100848| 0.22088799499488057| -0.2198097742999088|
| -0.7956806982100194|  0.8769731315965302| 0.40345617202874023| -0.9865387265800113|
|  0.1425148184896331| -1.0367370435405154| 0.14982249213986978|  -0.383192917437254|
|-0.46710129420075386| -0.8181073084540461|  0.3382931502749665| -1.0727028827533285|
|-0.37209655721166823|-0.27507683130518373| -0.5118276100477557|-0.20761693817955781|
| 0.04312852995066962|-0.40975988954530673|-0.29048538462740375|  -1.793666071268074|
+--------------------+--------------------+--------------------+--------------------+

In [15]:
pdf

                   A         B         C         D
2013-01-01 -0.442339  0.684567  0.220888 -0.219810
2013-01-02 -0.795681  0.876973  0.403456 -0.986539
2013-01-03  0.142515 -1.036737  0.149822 -0.383193
2013-01-04 -0.467101 -0.818107  0.338293 -1.072703
2013-01-05 -0.372097 -0.275077 -0.511828 -0.207617
2013-01-06  0.043129 -0.409760 -0.290485 -1.793666

In [16]:
psdf.head()

                   A         B         C         D
2013-01-01 -0.442339  0.684567  0.220888 -0.219810
2013-01-02 -0.795681  0.876973  0.403456 -0.986539
2013-01-03  0.142515 -1.036737  0.149822 -0.383193
2013-01-04 -0.467101 -0.818107  0.338293 -1.072703
2013-01-05 -0.372097 -0.275077 -0.511828 -0.207617

In [17]:
psdf.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq=None)

In [18]:
psdf.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [19]:
psdf.to_numpy()

/Users/saidakbar/Documents/innowise/pyspark/venv/lib/python3.12/site-packages/pyspark/pandas/utils.py:1053: PandasAPIOnSparkAdviceWarning: `to_numpy` loads all data into the driver's memory. It should only be used if the resulting NumPy ndarray is expected to be small.
  warnings.warn(message, PandasAPIOnSparkAdviceWarning)

array([[-0.4423389 ,  0.68456685,  0.22088799, -0.21980977],
       [-0.7956807 ,  0.87697313,  0.40345617, -0.98653873],
       [ 0.14251482, -1.03673704,  0.14982249, -0.38319292],
       [-0.46710129, -0.81810731,  0.33829315, -1.07270288],
       [-0.37209656, -0.27507683, -0.51182761, -0.20761694],
       [ 0.04312853, -0.40975989, -0.29048538, -1.79366607]])

In [20]:
psdf.describe()

26/10/27 10:40:31 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.315262 -0.163024  0.051691 -0.777255
std    0.349640  0.783064  0.368449  0.625252
min   -0.795681 -1.036737 -0.511828 -1.793666
25%   -0.467101 -0.818107 -0.290485 -1.072703
50%   -0.442339 -0.409760  0.149822 -0.986539
75%    0.043129  0.684567  0.338293 -0.219810
max    0.142515  0.876973  0.403456 -0.207617

In [21]:
psdf.sort_values(by='B')

                   A         B         C         D
2013-01-03  0.142515 -1.036737  0.149822 -0.383193
2013-01-04 -0.467101 -0.818107  0.338293 -1.072703
2013-01-06  0.043129 -0.409760 -0.290485 -1.793666
2013-01-05 -0.372097 -0.275077 -0.511828 -0.207617
2013-01-01 -0.442339  0.684567  0.220888 -0.219810
2013-01-02 -0.795681  0.876973  0.403456 -0.986539